// app/(public)/vehicles/_actions/car-database.ts
import { Car } from "@/types/car";

const convertToAED = (usdPrice: number): number => {
  return Math.round(usdPrice/10 * 2) * 10;
};

// This is our updated car database featuring the cars from the client's collection
export const carsDatabase: Car[] = [
  {
    id: "mercedes-s-class",
    name: "Mercedes-Benz S-Class 4MATIC",
    image: "/cars/mercedes-s-class-4matic-black.jpg",
    images: [
      "/cars/mercedes-s-class-4matic-black.jpg",
      "/cars/mercedes-s-class-4matic-white.jpg",
      "/cars/mercedes-s-class-4matic-white-2.jpg",
    ],
    rating: 4.9,
    reviews: 186,
    passengers: 5,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: convertToAED(220),
    category: "luxury",
    brand: "mercedes",
    description: "The Mercedes-Benz S-Class 4MATIC represents the pinnacle of luxury and technology in the automotive world. With its opulent interior, cutting-edge features, and exceptional comfort, it delivers an unmatched premium experience with the added capability of all-wheel drive.",
    specs: {
      engine: "3.0L Inline-6 with EQ Boost",
      power: "429 hp",
      torque: "520 Nm",
      acceleration: "4.9 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "8.2 L/100km",
      driveTrain: "AWD (4MATIC)",
      features: [
        "MBUX with augmented reality",
        "Burmester 4D surround sound",
        "Active ambient lighting",
        "E-Active body control",
        "Rear-wheel steering",
        "Digital Light headlights",
        "Executive rear seats",
        "Interior assistant"
      ]
    }
  },
  {
    id: "mercedes-amg-g63",
    name: "Mercedes-AMG G63",
    image: "/cars/mercedes-amg-g63.jpg",
    images: [
      "/cars/mercedes-amg-g63.jpg",
      "/cars/mercedes-amg-g63-black.jpg",
      "/cars/mercedes-amg-g63-mate-black.jpg",
      "/cars/mercedes-amg-g63-white.jpg",
    ],
    rating: 4.8,
    reviews: 142,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(350),
    category: "luxury",
    brand: "mercedes",
    description: "The Mercedes-AMG G63 is an iconic luxury SUV that combines rugged off-road capability with exceptional performance and prestige. This legendary G-Class offers a handcrafted AMG engine, sophisticated luxury, and unmistakable design that makes a powerful statement wherever you go.",
    specs: {
      engine: "4.0L V8 Biturbo",
      power: "577 hp",
      torque: "850 Nm",
      acceleration: "4.5 sec (0-100 km/h)",
      topSpeed: "220 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "13.1 L/100km",
      driveTrain: "AWD",
      features: [
        "AMG DYNAMIC SELECT",
        "Burmester surround sound system",
        "Adaptive suspension",
        "Nappa leather upholstery",
        "AMG performance exhaust",
        "MBUX infotainment system",
        "Heated and ventilated seats",
        "360° camera"
      ]
    }
  },
  {
    id: "rolls-royce-cullinan",
    name: "Rolls-Royce Cullinan",
    image: "/cars/rolls-royce-cullinan.jpg",
    images: [
      "/cars/rolls-royce-cullinan.jpg",
      "/cars/rolls-royce-cullinan-white.jpg",
      "/cars/rolls-royce-cullinan-white-2.jpg",
    ],
    rating: 4.9,
    reviews: 78,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(550),
    category: "luxury",
    brand: "rolls-royce",
    description: "The Rolls-Royce Cullinan is the first all-terrain SUV from Rolls-Royce, delivering effortless luxury everywhere. Named after the largest diamond ever discovered, the Cullinan offers uncompromised comfort with exceptional performance on any terrain, embodying the ultimate in automotive elegance.",
    specs: {
      engine: "6.75L Twin-Turbo V12",
      power: "563 hp",
      torque: "850 Nm",
      acceleration: "5.2 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "15.0 L/100km",
      driveTrain: "AWD",
      features: [
        "Bespoke leather interior",
        "Starlight headliner",
        "Viewing suite",
        "Adaptive air suspension",
        "Night vision with pedestrian recognition",
        "Picnic tables",
        "Champagne cooler",
        "Custom-crafted audio system"
      ]
    }
  },
  {
    id: "bentley-continental-gt",
    name: "Bentley Continental GT V8",
    image: "/cars/bentley-continental-gt-v8.jpg",
    images: [
      "/cars/bentley-continental-gt-v8.jpg",
      "/cars/bentley-continental-gt-azure.jpg",
    ],
    rating: 4.7,
    reviews: 124,
    passengers: 4,
    airConditioning: true,
    doors: 2,
    transmission: "Auto",
    price: convertToAED(380),
    category: "luxury",
    brand: "bentley",
    description: "The Bentley Continental GT V8 combines power and elegance in a grand touring package. With its distinctive styling, exquisite handcrafted interior, and powerful V8 engine, it offers an exceptional driving experience that blends performance with British luxury craftsmanship.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      power: "542 hp",
      torque: "770 Nm",
      acceleration: "4.0 sec (0-100 km/h)",
      topSpeed: "318 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "11.2 L/100km",
      driveTrain: "AWD",
      features: [
        "Handcrafted wood veneers",
        "Naim for Bentley audio system",
        "Rotating display",
        "Active all-wheel drive",
        "Air suspension with continuous damping control",
        "Massage seats",
        "City Specification and Touring Specification",
        "Mood lighting"
      ]
    }
  },
  {
    id: "bentley-bentayga-azure",
    name: "Bentley Bentayga Azure",
    image: "/cars/bentley-bentayga-azure.jpg",
    images: [
      "/cars/bentley-bentayga-azure.jpg",
    ],
    rating: 4.8,
    reviews: 96,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(410),
    category: "luxury",
    brand: "bentley",
    description: "The Bentley Bentayga Azure represents the pinnacle of luxury SUVs, combining extraordinary performance with unparalleled comfort. The Azure specification enhances wellbeing with unique design elements and increased comfort features, ensuring a serene driving experience in the most opulent surroundings.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      power: "542 hp",
      torque: "770 Nm",
      acceleration: "4.5 sec (0-100 km/h)",
      topSpeed: "290 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "13.0 L/100km",
      driveTrain: "AWD",
      features: [
        "Wellness quilted seats",
        "Azure illuminated treadplates",
        "Naim for Bentley premium audio",
        "Bentley Dynamic Ride",
        "Front seat comfort specification",
        "Mood lighting",
        "Head-up display",
        "Night vision"
      ]
    }
  },
  {
    id: "range-rover-sport-sv",
    name: "Range Rover Sport SV",
    image: "/cars/range-rover-sport-sv.jpg",
    images: [
      "/cars/range-rover-sport-sv.jpg",
      "/cars/range-rover-sport.jpg",
      "/cars/range-rover-sport-black.jpg",
    ],
    rating: 4.7,
    reviews: 135,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(300),
    category: "suv",
    brand: "range-rover",
    description: "The Range Rover Sport SV delivers extraordinary performance combined with Range Rover's legendary capability and refinement. This high-performance SUV features exclusive SV enhancements, bespoke design elements, and track-inspired dynamics while maintaining the luxury and versatility expected from Range Rover.",
    specs: {
      engine: "4.4L Twin-Turbo V8",
      power: "626 hp",
      torque: "750 Nm",
      acceleration: "3.8 sec (0-100 km/h)",
      topSpeed: "290 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "11.7 L/100km",
      driveTrain: "AWD",
      features: [
        "SV Performance seats",
        "Carbon fiber trim",
        "Meridian™ Signature Sound System",
        "SV-tuned Dynamic Air Suspension",
        "Carbon ceramic brakes",
        "All-terrain Response 3",
        "Active electronic differential",
        "Adaptive Dynamics"
      ]
    }
  },
  {
    id: "range-rover-vogue-hse",
    name: "Range Rover Vogue HSE",
    image: "/cars/range-rover-vogue-hse-black.jpg",
    images: [
      "/cars/range-rover-vogue-hse-black.jpg",
      "/cars/range-rover-vogue-hse-gray.jpg",
      "/cars/range-rover-vogue-hse-white-2.jpg",
    ],
    rating: 4.8,
    reviews: 156,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(290),
    category: "suv",
    brand: "range-rover",
    description: "The Range Rover Vogue HSE embodies luxury, sophistication, and capability in a full-size SUV package. With its distinctive design, advanced technology, and refined driving dynamics, it offers an exceptional experience whether traversing urban landscapes or venturing off-road.",
    specs: {
      engine: "3.0L P400 Inline-6 MHEV",
      power: "395 hp",
      torque: "550 Nm",
      acceleration: "5.8 sec (0-100 km/h)",
      topSpeed: "242 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "9.4 L/100km",
      driveTrain: "AWD",
      features: [
        "Semi-aniline leather seats",
        "Meridian™ 3D Surround Sound",
        "Executive Class Comfort-Plus rear seats",
        "Terrain Response 2",
        "Pixel LED headlights",
        "Active Noise Cancellation",
        "Cabin Air Purification Pro",
        "Advanced Driver Assistance"
      ]
    }
  },
  {
    id: "range-rover-velar-rdynamic",
    name: "Range Rover Velar R-Dynamic",
    image: "/cars/range-rover-velar-r-dynamic.jpg",
    images: [
      "/cars/range-rover-velar-r-dynamic.jpg",
    ],
    rating: 4.6,
    reviews: 118,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(210),
    category: "suv",
    brand: "range-rover",
    description: "The Range Rover Velar R-Dynamic combines avant-garde design with enhanced performance features. Its minimalist exterior, technical interior and refined driving dynamics create a compelling modern luxury SUV that stands out with its distinctive personality and striking presence.",
    specs: {
      engine: "2.0L P300 Turbocharged",
      power: "300 hp",
      torque: "400 Nm",
      acceleration: "6.5 sec (0-100 km/h)",
      topSpeed: "234 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "8.2 L/100km",
      driveTrain: "AWD",
      features: [
        "Perforated Windsor leather seats",
        "R-Dynamic styling package",
        "Pivi Pro dual touchscreen",
        "Configurable Dynamics",
        "Adaptive Dynamics",
        "Matrix LED headlights",
        "Premium Textile and Kvadrat interior option",
        "Meridian™ Sound System"
      ]
    }
  },
  {
    id: "porsche-911-carrera-gts",
    name: "Porsche 911 Carrera GTS",
    image: "/cars/porsche-911-carrera-gts-blue.jpg",
    images: [
      "/cars/porsche-911-carrera-gts-blue.jpg",
      "/cars/porsche-911-targa-black.jpg",
      "/cars/porsche-911-targa-green.jpg",
    ],
    rating: 4.8,
    reviews: 142,
    passengers: 2,
    airConditioning: true,
    doors: 2,
    transmission: "Auto",
    price: convertToAED(360),
    category: "sports",
    brand: "porsche",
    description: "The Porsche 911 Carrera GTS bridges the gap between the standard Carrera and the track-focused GT3. With enhanced power, bespoke styling cues, and performance-focused equipment, it offers driving enthusiasts the perfect balance of everyday usability and thrilling performance.",
    specs: {
      engine: "3.0L Twin-Turbo Flat-6",
      power: "473 hp",
      torque: "570 Nm",
      acceleration: "3.4 sec (0-100 km/h)",
      topSpeed: "312 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "10.7 L/100km",
      driveTrain: "RWD",
      features: [
        "Sport Chrono Package",
        "PASM sport suspension",
        "Sports exhaust system",
        "Race-Tex interior trim",
        "Porsche Dynamic Light System Plus",
        "Porsche Torque Vectoring",
        "20/21-inch RS Spyder Design wheels",
        "Bose surround sound system"
      ]
    }
  },
  {
    id: "mercedes-amg-gt-4door",
    name: "Mercedes-AMG GT 4-Door",
    image: "/cars/mercedes-amg-gt-4doors.jpg",
    images: [
      "/cars/mercedes-amg-gt-4doors.jpg",
    ],
    rating: 4.7,
    reviews: 98,
    passengers: 4,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: convertToAED(330),
    category: "sports",
    brand: "mercedes",
    description: "The Mercedes-AMG GT 4-Door combines the thrilling performance of a sports car with the practicality of a four-door coupe. With its handcrafted AMG engine, advanced technology, and luxurious interior, it offers a compelling blend of everyday usability and exhilarating driving dynamics.",
    specs: {
      engine: "4.0L V8 Biturbo",
      power: "630 hp",
      torque: "900 Nm",
      acceleration: "3.2 sec (0-100 km/h)",
      topSpeed: "315 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "12.5 L/100km",
      driveTrain: "AWD",
      features: [
        "AMG Performance 4MATIC+",
        "AMG RIDE CONTROL+",
        "Widescreen cockpit",
        "AMG Performance steering wheel",
        "Active rear-wheel steering",
        "Burmester surround sound",
        "AMG Track Pace",
        "Drift mode"
      ]
    }
  },
  {
    id: "lamborghini-urus",
    name: "Lamborghini Urus",
    image: "/cars/lamborghini-urus.jpg",
    images: [
      "/cars/lamborghini-urus.jpg",
      "/cars/lamborghini-urus-gray.jpg",
    ],
    rating: 4.8,
    reviews: 112,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(420),
    category: "suv",
    brand: "lamborghini",
    description: "The Lamborghini Urus is the world's first Super Sport Utility Vehicle. It combines the soul of a super sports car with the functionality of an SUV, creating a vehicle that's as comfortable on the racetrack as it is on rough terrain or urban streets.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      power: "650 hp",
      torque: "850 Nm",
      acceleration: "3.6 sec (0-100 km/h)",
      topSpeed: "305 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "12.7 L/100km",
      driveTrain: "AWD",
      features: [
        "ANIMA Selector with 6 driving modes",
        "Adaptive air suspension",
        "Carbon ceramic brakes",
        "Active roll stabilization",
        "B&O 3D advanced sound system",
        "Alcantara and leather interior",
        "Lamborghini Infotainment System III",
        "Rear-wheel steering"
      ]
    }
  },
  {
    id: "cadillac-escalade-v",
    name: "Cadillac Escalade V",
    image: "/cars/cadillac-escalade-v.jpg",
    images: [
      "/cars/cadillac-escalade-v.jpg",
      "/cars/cadillac-escalade.jpg",
    ],
    rating: 4.6,
    reviews: 87,
    passengers: 7,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(280),
    category: "suv",
    brand: "cadillac",
    description: "The Cadillac Escalade V is the first-ever high-performance full-size luxury SUV from Cadillac's V-Series. It combines the Escalade's iconic presence and luxury with supercharged performance, distinctive sound, and extraordinary driving dynamics to create a truly unique vehicle.",
    specs: {
      engine: "6.2L Supercharged V8",
      power: "682 hp",
      torque: "885 Nm",
      acceleration: "4.4 sec (0-100 km/h)",
      topSpeed: "200 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "16.8 L/100km",
      driveTrain: "AWD",
      features: [
        "AKG Studio Reference 36-speaker audio",
        "38-inch curved OLED display",
        "V-Mode personalized performance settings",
        "Magnetic Ride Control 4.0",
        "Semi-aniline leather seats",
        "Super Cruise hands-free driving",
        "Night Vision",
        "Adjustable air suspension"
      ]
    }
  },
  {
    id: "ferrari-roma",
    name: "Ferrari Roma",
    image: "/cars/ferrari-roma.jpg",
    images: [
      "/cars/ferrari-roma.jpg",
    ],
    rating: 4.9,
    reviews: 76,
    passengers: 2,
    airConditioning: true,
    doors: 2,
    transmission: "Auto",
    price: convertToAED(460),
    category: "sports",
    brand: "ferrari",
    description: "The Ferrari Roma embodies 'La Nuova Dolce Vita' with its timeless and refined design. This elegant grand touring Ferrari combines exceptional performance with versatility and comfort, making it perfect for everyday driving while maintaining the thrilling experience expected of the Prancing Horse.",
    specs: {
      engine: "3.9L Twin-Turbo V8",
      power: "620 hp",
      torque: "760 Nm",
      acceleration: "3.4 sec (0-100 km/h)",
      topSpeed: "320 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "11.2 L/100km",
      driveTrain: "RWD",
      features: [
        "8-speed dual-clutch transmission",
        "Ferrari Side Slip Control 6.0",
        "Manettino driving mode selector",
        "Digital driver display",
        "16-inch curved HD touchscreen",
        "Full-grain Frau leather interior",
        "Carbon fiber steering wheel with LED shift lights",
        "Advanced driver assistance systems"
      ]
    }
  },
  {
    id: "chevrolet-corvette-stingray",
    name: "Chevrolet Corvette Stingray",
    image: "/cars/chevrolet-corvette-stingray.jpg",
    images: [
      "/cars/chevrolet-corvette-stingray.jpg",
    ],
    rating: 4.7,
    reviews: 132,
    passengers: 2,
    airConditioning: true,
    doors: 2,
    transmission: "Auto",
    price: convertToAED(240),
    category: "sports",
    brand: "chevrolet",
    description: "The Chevrolet Corvette Stingray represents a revolution in the iconic American sports car's history. With its mid-engine configuration, aggressive styling, and track-capable performance, it delivers an exhilarating driving experience that rivals exotic supercars at a fraction of the price.",
    specs: {
      engine: "6.2L V8",
      power: "495 hp",
      torque: "637 Nm",
      acceleration: "2.9 sec (0-100 km/h)",
      topSpeed: "312 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "12.0 L/100km",
      driveTrain: "RWD",
      features: [
        "8-speed dual-clutch transmission",
        "Magnetic Ride Control 4.0",
        "Performance data recorder",
        "Head-up display",
        "Bose Performance Series audio",
        "Front lift system",
        "Z51 Performance Package option",
        "Driver mode selector with 12 settings"
      ]
    }
  },
  {
    id: "toyota-corolla",
    name: "Toyota Corolla",
    image: "/cars/toyota-corolla.jpg",
    images: [
      "/cars/toyota-corolla.jpg",
    ],
    rating: 4.3,
    reviews: 198,
    passengers: 5,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: convertToAED(70),
    category: "economy",
    brand: "toyota",
    description: "The Toyota Corolla continues its legacy as one of the world's most popular compact cars. Known for its reliability, efficiency and value, the latest generation adds dynamic styling, improved performance, and enhanced technology while maintaining the practical qualities that have made it a global bestseller.",
    specs: {
      engine: "1.8L Inline-4",
      power: "139 hp",
      torque: "172 Nm",
      acceleration: "10.2 sec (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "6.0 L/100km",
      driveTrain: "FWD",
      features: [
        "Toyota Safety Sense 2.0",
        "8-inch touchscreen",
        "Apple CarPlay & Android Auto",
        "Automatic climate control",
        "LED headlights",
        "60/40 split rear seats",
        "Smart key with push button start",
        "Backup camera"
      ]
    }
  },
  {
    id: "kia-cerato",
    name: "Kia Cerato",
    image: "/cars/kia-cerato.jpg",
    images: [
      "/cars/kia-cerato.jpg",
    ],
    rating: 4.2,
    reviews: 156,
    passengers: 5,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: convertToAED(65),
    category: "economy",
    brand: "kia",
    description: "The Kia Cerato offers a compelling blend of style, technology, and value in the compact sedan segment. With its modern design, comfortable interior, and comprehensive suite of features, it provides an elevated driving experience without the premium price tag.",
    specs: {
      engine: "2.0L Inline-4",
      power: "147 hp",
      torque: "179 Nm",
      acceleration: "9.8 sec (0-100 km/h)",
      topSpeed: "195 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "6.7 L/100km",
      driveTrain: "FWD",
      features: [
        "8-inch touchscreen infotainment",
        "Wireless Apple CarPlay & Android Auto",
        "Smart key with push-button start",
        "Advanced driver assistance systems",
        "Dual-zone automatic climate control",
        "Synthetic leather seating surfaces",
        "60/40 split-folding rear seats",
        "LED headlights and taillights"
      ]
    }
  },
  {
    id: "fiat-500",
    name: "Fiat 500",
    image: "/cars/fiat-500.jpg",
    images: [
      "/cars/fiat-500.jpg",
    ],
    rating: 4.1,
    reviews: 124,
    passengers: 4,
    airConditioning: true,
    doors: 3,
    transmission: "Auto",
    price: convertToAED(55),
    category: "economy",
    brand: "fiat",
    description: "The Fiat 500 combines Italian style with city-friendly dimensions in a charming package. Its retro-inspired design, nimble handling, and efficient performance make it perfect for urban environments, while its distinctive personality ensures it stands out from the crowd.",
    specs: {
      engine: "1.0L Inline-3 Hybrid",
      power: "70 hp",
      torque: "92 Nm",
      acceleration: "12.8 sec (0-100 km/h)",
      topSpeed: "167 km/h",
      fuelType: "Gasoline Hybrid",
      fuelConsumption: "4.6 L/100km",
      driveTrain: "FWD",
      features: [
        "7-inch touchscreen display",
        "Apple CarPlay & Android Auto",
        "Panoramic glass roof option",
        "Uconnect infotainment system",
        "City driving mode",
        "Rear parking sensors",
        "15-inch alloy wheels",
        "6-speaker audio system"
      ]
    }
  },
  {
    id: "hyundai-staria",
    name: "Hyundai Staria (11 Passengers)",
    image: "/cars/hyundai-staria-11-passengers.jpg",
    images: [
      "/cars/hyundai-staria-11-passengers.jpg",
    ],
    rating: 4.4,
    reviews: 86,
    passengers: 11,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(190),
    category: "minivan",
    brand: "hyundai",
    description: "The Hyundai Staria represents a bold new vision for MPVs with its futuristic design and exceptional space. This 11-passenger variant maximizes practicality while delivering a premium experience, making it ideal for large families, group travel, or commercial transport applications.",
    specs: {
      engine: "2.2L CRDi Diesel",
      power: "177 hp",
      torque: "431 Nm",
      acceleration: "12.4 sec (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelType: "Diesel",
      fuelConsumption: "7.5 L/100km",
      driveTrain: "FWD",
      features: [
        "11-seat configuration",
        "10.25-inch touchscreen infotainment",
        "Wireless charging",
        "Ambient interior lighting",
        "Smart power sliding doors",
        "Full-range safety systems",
        "Multi-zone climate control",
        "Interior camera to monitor rear passengers"
      ]
    }
  },
  {
    id: "kia-carnival",
    name: "Kia Carnival",
    image: "/cars/kia-carival.jpg",
    images: [
      "/cars/kia-carival.jpg",
    ],
    rating: 4.5,
    reviews: 94,
    passengers: 8,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(170),
    category: "minivan",
    brand: "kia",
    description: "The Kia Carnival redefines the minivan segment with its SUV-inspired design and premium features. It delivers exceptional interior space, versatile seating configurations, and advanced technology to provide a sophisticated transportation solution for families and VIP transport services.",
    specs: {
      engine: "3.5L V6",
      power: "290 hp",
      torque: "355 Nm",
      acceleration: "8.5 sec (0-100 km/h)",
      topSpeed: "190 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "9.6 L/100km",
      driveTrain: "FWD",
      features: [
        "Dual power sliding doors",
        "12.3-inch touchscreen infotainment",
        "Passenger view camera",
        "Dual sunroof",
        "Premium relaxation seats",
        "Smart power tailgate",
        "Bose premium audio",
        "Comprehensive safety suite"
      ]
    }
  },
  {
    id: "mercedes-maybach-gls",
    name: "Mercedes-Maybach GLS",
    image: "/cars/mercedes-maybach-gls.jpg",
    images: [
      "/cars/mercedes-maybach-gls.jpg",
    ],
    rating: 4.9,
    reviews: 68,
    passengers: 4,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: convertToAED(490),
    category: "luxury",
    brand: "mercedes",
    description: "The Mercedes-Maybach GLS represents the ultimate luxury SUV experience. It combines the commanding presence and capability of the GLS with the exceptional refinement and exclusivity of Maybach to create a vehicle that delivers first-class comfort with the versatility of an SUV.",
    specs: {
      engine: "4.0L V8 Biturbo",
      power: "550 hp",
      torque: "730 Nm",
      acceleration: "4.9 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "11.7 L/100km",
      driveTrain: "AWD",
      features: [
        "Maybach Executive Rear Seats",
        "Folding tables in rear",
        "Champagne flutes and refrigerator",
        "E-ACTIVE BODY CONTROL suspension",
        "Burmester® High-End 3D Surround Sound",
        "MBUX Rear Tablet",
        "Night View Assist Plus",
        "Maybach Exclusive nappa leather"
      ]
    }
  }
];
